

services:
  safe4work-dev:
    container_name: safe4work-dev
    build: .
    ports:
      - "5080:8080" #Using ports that are hopefully available. format is: 80XX
      - "5443:443" #Using ports that are hopefully available. format is: 443XX (available range is 44300–44399)
    extra_hosts:
      - "host.docker.internal:host-gateway"
#      - "authentik.docker.local:172.28.0.2"
    volumes:
     - "../:/var/www/html"
     - "./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
     - "./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"
    environment:
      LEAN_DB_HOST: 'safe4work-db'
      LEAN_DB_USER: 'safe4work'
      LEAN_DB_PASSWORD: 'safe4work'
      LEAN_DB_DATABASE: 'safe4work'
      LEAN_DB_PORT: '3306'

    depends_on:
      safe4work-db:
        condition: service_healthy
    networks:
      - safe4work_internal
#      - traefik
#    labels:
#      - "traefik.enable=true"
#      - "traefik.priority=2"
#      - "traefik.docker.network=traefik"
#
#      # HTTP Router
#      - "traefik.http.routers.leantime.rule=Host(`leantime.docker.local`)"
#      - "traefik.http.services.leantime.loadbalancer.server.port=8080"
#      - "traefik.http.routers.leantime.tls=true"


  safe4work-redis:
    container_name: safe4work-redis
    image: redis:4.0
    ports:
      - "6379"
    networks:
      - safe4work_internal
  safe4work-db:
    image: mysql:8.4
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'safe4work'
      MYSQL_USER: 'safe4work'
      MYSQL_PASSWORD: 'safe4work'
      MYSQL_DATABASE: 'safe4work'
    networks:
      - safe4work_internal
    volumes:
      - safe4work-mysql:/var/lib/mysql:rw
    healthcheck:
      test: "mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1'"
      interval: 5s
      timeout: 5s
      retries: 20

  selenium:
    image: selenium/standalone-chromium
    shm_size: 2gb
    environment:
      - SCREEN_WIDTH=2560
      - SCREEN_HEIGHT=1440
    ports:
      - "4444"
      - "7900"
    networks:
      - safe4work_internal
  maildev:
    image: maildev/maildev
    environment:
      - MAILDEV_SMTP_PORT=465
      - MAILDEV_WEB_PORT=8081
    ports:
      - "8081"
    networks:
      - safe4work_internal
  s3ninja:
    image: scireum/s3-ninja
    ports:
      - "8083"
    networks:
      - safe4work_internal
    volumes:
      - s3ninja-data:/home/sirius/data


networks:
  safe4work_internal:
    driver: bridge
    name: safe4work_internal
#  traefik:
#    external: true
#    name: traefik

volumes:
  safe4work-mysql:
  s3ninja-data:
